name: Piqued
favicon: null
layout_spectrum: 0.13778154063038528
typography_spectrum: 0.7354564694687724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7904512248933315
  lightness: 0.11709134723059833
  saturation: 0.6358190893661231
  rhythmicContrast: 0.3437540407758206
purpose: []
